name: Mobile CI/CD

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'packages/mobile/**'
      - 'packages/shared/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'packages/mobile/**'
      - 'packages/shared/**'

env:
  NODE_VERSION: '18'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build shared package
        run: npm run build --workspace=packages/shared
        
      - name: Lint Mobile packages
        run: |
          npm run lint --workspace=packages/shared --if-present
          npm run lint --workspace=packages/mobile
          
      - name: Type check Mobile packages
        run: |
          npm run type-check --workspace=packages/shared --if-present
          npm run type-check --workspace=packages/mobile --if-present
          
      - name: Run Mobile tests
        run: |
          npm run test --workspace=packages/shared --if-present
          npm run test --workspace=packages/mobile --if-present
          
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Security audit
        run: npm audit --audit-level=moderate
        
      - name: Check for outdated dependencies
        run: npm outdated || true