name: Deploy Web App

on:
  push:
    branches: [main, master]
    paths: 
      - 'packages/web/**'
      - 'packages/shared/**'
      - '.github/workflows/web-deploy.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'packages/web/**'
      - 'packages/shared/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build shared package
        run: npm run build --workspace=packages/shared
        
      - name: Lint Web package
        run: npm run lint --workspace=packages/web
        
      - name: Build Web package
        run: npm run build --workspace=packages/web
        env:
          NODE_ENV: production
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_VAPID_PUBLIC_KEY: ${{ secrets.REACT_APP_VAPID_PUBLIC_KEY }}
          
      - name: Run tests
        run: npm run test --workspace=packages/web -- --watchAll=false --coverage
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: packages/web/dist
          retention-days: 30
          
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: packages/web
          vercel-args: '--prod'
          
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: packages/web
          
      - name: Deploy to Netlify (Alternative)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: packages/web/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: .lighthouserc.js
          uploadArtifacts: true
          temporaryPublicStorage: true
          
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run security audit
        run: npm audit --audit-level=high
        
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://your-app-url.vercel.app'